### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by xinruozhishui** [go-cq/cq#33]
I tried to run example, 401 Unauthorized error message returned.How to connect db authorized?

**Comment by freeeve** [comment]
See the example url in conn_test.go:

`http://neo4j:test@localhost:7474/`

**Comment by tithamane** [comment]
@freeeve - Maybe this should be added on the readme? I opened this issue just to see how it's done

**Comment by freeeve** [comment]
@tithamane good idea, I added it to the MVS.
